Option Explicit

' *****************************************************************************************
' Purpose:     This script creates a sketch containing N squares within a Part document (N: user defined)
' Assumptions: A Part document must be active.
' Author:      Antonio Trillo DÃ­az (antonio.trillo.diaz@gmail.com)
' Created:     17/09/2014
' Last updated:24/09/2014
' *****************************************************************************************

' *****************************************************************************************
' Features to be included:
' * Error handling if no Part Document is open.
' *****************************************************************************************
 
Sub CATMain()
 
' New CATPart application --------------------------------------------

Dim Component As Part
Dim Doc As Document
'Set Doc = CATIA.Documents.Add("Part") /Comment if there is no Part open
Set Doc = CATIA.ActiveDocument
Set Component = Doc.Part

' List Object Sketches Generation -----------------------------------

Dim Sketch As Sketches
Set Sketch = Component.MainBody.Sketches

' Reference Level Generation -------------------------------------------

Dim ElementsOrigin, Level
Set ElementsOrigin = Component.OriginElements
Set Level = ElementsOrigin.PlaneYZ

' Object Sketch Generation -------------------------------------------

Dim Sktch As Sketch
Set Sktch = Sketch.Add(Level)

' 2D Tool Box Generation and Sktech Definition ---------------------

Dim Wzk As Factory2D
Set Wzk = Sktch.OpenEdition

' Geometry Generation -----------------------------------------------

Dim Linea As Line2D

Dim Value As Double
Value = InputBox("Enter the width:", "Part Creation", 100)

Dim Number As Integer
Number = InputBox("Number of squares:", "Part Creation", 1)

Dim i As Integer

For i = 1 To Number
    Value = i * Value
    Set Linea = Wzk.CreateLine(-Value / 2, Value / 2, Value / 2, Value / 2)
    Set Linea = Wzk.CreateLine(Value / 2, Value / 2, Value / 2, -Value / 2)
    Set Linea = Wzk.CreateLine(Value / 2, -Value / 2, -Value / 2, -Value / 2)
    Set Linea = Wzk.CreateLine(-Value / 2, -Value / 2, -Value / 2, Value / 2)

Next

' Sketch Closing and Component Update -----------------------

Sktch.CloseEdition
Component.Update

End Sub
